### ISSUE TITLE
Realizar entrevista com cliente

### ISSUE THREAD

**Issue by passolargo** [IF977/StatusService#2]
Como membro da equipe.
Para que possa desenvolver o projeto.
Eu quero realizar uma entrevista com um usuario em potencial da minha aplicação.

**Comment by Augusto94** [comment]
![ata da entrevista com o cliente](https://cloud.githubusercontent.com/assets/17787525/14473119/f3ea3398-00cc-11e6-89d4-ed929a6dbd51.jpg)
